# Generated by Django 6.0 on 2026-01-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('T20', 'T20'), ('TEST', 'Test Match')], max_length=10)),
                ('custom_overs', models.IntegerField(blank=True, help_text='Total overs per innings for limited overs', null=True)),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=4, null=True)),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='SETUP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_captain', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.IntegerField()),
                ('is_declared', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('overs_bowled', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='api.match')),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='api.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='api.team')),
            ],
            options={
                'ordering': ['innings_number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='best_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_batsman_awards', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='best_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_bowler_awards', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='man_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom_awards', to='api.player'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField()),
                ('ball_number', models.IntegerField()),
                ('runs_batter', models.IntegerField(default=0)),
                ('extras', models.IntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('WD', 'Wide'), ('NB', 'No Ball'), ('B', 'Bye'), ('LB', 'Leg Bye'), ('NONE', 'None')], default='NONE', max_length=5)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(choices=[('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.innings')),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='api.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='api.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker_balls', to='api.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outs', to='api.player')),
            ],
            options={
                'ordering': ['innings', 'over_number', 'ball_number'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_wins', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='api.team'),
        ),
    ]
