# Generated by Django 6.0 on 2026-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_man_standing',
            field=models.BooleanField(default=False),
        ),
    ]
