# Generated by Django 6.0 on 2026-01-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_last_man_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='catcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='api.player'),
        ),
    ]
